openapi: 3.0.0
x-stoplight:
  id: pam6c7ofp4gpt
info:
  title: Fitnesstagebuch
  version: '1.0'
  description: 'Ein Fitnesstagbeuch, das eine Auswahl an Übungen zur Verfügung stellt, aus denen man sich ein Musterworkout-Template zusammenstellen kann.'
  contact:
    name: 'Yannick, Jan, Jasmina, Leon'
servers:
  - url: 'http://localhost:3000'
    description: Lokale Entwicklung
paths:
  /exercise:
    get:
      summary: GET
      tags:
        - Exercise
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
      operationId: get-exercise
      parameters:
        - schema:
            type: string
          in: query
          name: name
        - schema:
            type: string
          in: query
          name: image
        - schema:
            type: string
          in: query
          name: difficulty
        - schema:
            type: string
          in: query
          name: muscleGroup
        - schema:
            type: string
          in: query
          name: description
      description: Suche Exercises
    post:
      summary: ''
      operationId: post-exercise
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
      description: Übung anlegen.
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: Übungsname
        - schema:
            type: string
          in: query
          name: image
          description: Bild
        - schema:
            type: string
          in: query
          name: difficulty
          description: Übungsschwierigkeit
        - schema:
            type: string
          in: query
          name: muscleGroup
          description: Muskelgruppe
        - schema:
            type: string
          in: query
          name: description
          description: Beschreibung
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              $ref: '#/components/schemas/Exercise'
  '/exercise/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Exercise lesen
      tags:
        - Exercise
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '404':
          description: Not Found
      operationId: get-exercise-id
      description: Details zu einzelner Übung
      parameters: []
    put:
      summary: Exercise überschreiben
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: put-exercise-id
      description: 'Um Daten zu überschreiben, müssen alle Felder überschrieben werden. '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
            examples: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      parameters: []
    patch:
      summary: Feld in Exercise ändern
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '404':
          description: Not Found
      operationId: patch-exercise-id
      description: 'Daten überschreiben, nur geänderte Felder müssen überschrieben werden.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
    delete:
      summary: Exercise löschen
      tags: []
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      operationId: delete-exercise-id
  /:
    get:
      summary: Wurzeladresse
      tags:
        - Start
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
      operationId: get
      description: HATEOAS Verlinkungen auf die einzelnen Collections
  /workout:
    post:
      summary: Erstelle Workout
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
      operationId: post-workout
      parameters:
        - schema:
            type: string
          in: query
          name: name
        - schema:
            type: string
          in: query
          name: exercises
    get:
      summary: Suche Workouts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'
      operationId: get-workout
      parameters:
        - schema:
            type: string
          in: query
          name: name
        - schema:
            type: string
          in: query
          name: exercises
  '/workout/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Einzelnes Workout suchen
      tags:
        - workout
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Not Found
      operationId: get-workout-id
    patch:
      summary: Einzelne Elemente des Workouts abändern
      tags:
        - workout
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Not Found
      operationId: patch-workout-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout'
        description: ''
    delete:
      summary: Workout loeschen
      tags:
        - workout
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: delete-workout-id
    put:
      summary: Workout abändern komplett
      tags:
        - workout
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: put-workout-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout'
        description: ''
components:
  schemas:
    Exercise:
      title: Exercise
      x-stoplight:
        id: 2qgclqxq5hrur
      type: object
      description: Eine Fitnessübung. Grundbaustein für Workouts.
      properties:
        _id:
          type: string
        name:
          type: string
        image:
          type: string
        difficulty:
          type: string
        muscleGroup:
          type: string
        description:
          type: string
        _links:
          $ref: '#/components/schemas/HATEOAS_Link'
    HATEOAS_Collection:
      title: HATEOAS_Collection
      x-stoplight:
        id: y4xgmkkpohyq3
      type: object
      description: HATEOAS Verlinkung zu iener einzelnen Collection.
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'
    HATEOAS_Link:
      title: HATEOAS_Link
      x-stoplight:
        id: q0216v3vf5fea
      type: object
      description: 'Definiert die Übung, URL und Query zum Aufruf der jeweiligen Aktion.'
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string
    HATEOAS_Ressource:
      title: HATEOAS_Ressource
      x-stoplight:
        id: 5nxs26rusfupb
      type: object
      description: Hateoas Verlinkung
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'
    Workout:
      title: Workout
      x-stoplight:
        id: eeoecvcyhn8zx
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'
        _links:
          $ref: '#/components/schemas/HATEOAS_Link'
tags:
  - name: Start


